<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ballbot">

  <xacro:property name="chassis_len" value="0.5"/>
  <xacro:property name="chassis_width" value="0.5"/>
  <xacro:property name="chassis_height" value="0.3"/>
  <xacro:property name="chassis_mass" value="3.0"/>
  <xacro:property name="chassis_z_offset" value="0.20"/> 

  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="wheel_mass" value="0.5"/>
  <xacro:property name="wheel_y_offset" value="0.27"/>
  <xacro:property name="wheel_z_offset" value="0.05"/>

  <xacro:property name="castor_radius" value="0.04"/>
  <xacro:property name="castor_mass" value="1.5"/>
  <xacro:property name="castor_x_offset" value="-0.2"/>

  <xacro:property name="arm_len" value="0.6"/>
  <xacro:property name="arm_width" value="0.05"/>
  <xacro:property name="arm_height" value="0.3"/>
  <xacro:property name="arm_mass" value="0.04"/>
  <xacro:property name="arm_angle" value="0.523"/> 
  <xacro:property name="flap_len" value="0.3"/>
  <xacro:property name="flap_width" value="0.02"/>
  <xacro:property name="flap_height" value="0.3"/>
  <xacro:property name="flap_mass" value="0.01"/>

  <material name="blue"><color rgba="0.0 0.0 0.8 1.0"/></material>
  <material name="black"><color rgba="0.0 0.0 0.0 1.0"/></material>
  <material name="grey"><color rgba="0.5 0.5 0.5 1.0"/></material>
  <material name="green"><color rgba="0.0 0.8 0.0 1.0"/></material>
  <material name="red"><color rgba="0.8 0.0 0.0 1.0"/></material>

  <xacro:macro name="box_inertia" params="m x y z">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m/12.0 * (y*y + z*z)}" ixy="0.0" ixz="0.0"
               iyy="${m/12.0 * (x*x + z*z)}" iyz="0.0"
               izz="${m/12.0 * (x*x + y*y)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m/12.0 * (3*r*r + h*h)}" ixy="0.0" ixz="0.0"
               iyy="${m/12.0 * (3*r*r + h*h)}" iyz="0.0"
               izz="${m/2.0 * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${2.0/5.0 * m * r*r}" ixy="0.0" ixz="0.0"
               iyy="${2.0/5.0 * m * r*r}" iyz="0.0"
               izz="${2.0/5.0 * m * r*r}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="drive_wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="0 ${reflect * wheel_y_offset} ${wheel_z_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <!-- CRITICAL FIX: Limits are required for Gazebo to apply effort -->
      <limit effort="50.0" velocity="20.0"/>
    </joint>

    <gazebo reference="${prefix}_wheel">
      <mu1>2.0</mu1>
      <mu2>2.0</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="collector_arm" params="prefix reflect angle limit_lower limit_upper">
    <link name="${prefix}_arm">
      <visual>
        <geometry>
          <box size="${arm_len} ${arm_width} ${arm_height}"/>
        </geometry>
        <material name="green"/>
      </visual>
      <collision>
        <geometry>
          <box size="${arm_len} ${arm_width} ${arm_height}"/>
        </geometry>
      </collision>
      <xacro:box_inertia m="${arm_mass}" x="${arm_len}" y="${arm_width}" z="${arm_height}"/>
    </link>

    <joint name="${prefix}_arm_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_arm"/>
      <origin xyz="0.51 ${reflect * 0.40} ${chassis_z_offset}" rpy="0 0 ${reflect * angle}"/>
    </joint>

    <link name="${prefix}_flap">
      <visual>
        <origin xyz="${flap_len/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${flap_len} ${flap_width} ${flap_height}"/>
        </geometry>
        <material name="red"/>
      </visual>
      <collision>
        <origin xyz="${flap_len/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${flap_len} ${flap_width} ${flap_height}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="${flap_len/2} 0 0" rpy="0 0 0"/>
        <mass value="${flap_mass}"/>
        <inertia ixx="${flap_mass/12.0 * (flap_width*flap_width + flap_height*flap_height)}" ixy="0.0" ixz="0.0"
                 iyy="${flap_mass/12.0 * (flap_len*flap_len + flap_height*flap_height)}" iyz="0.0"
                 izz="${flap_mass/12.0 * (flap_len*flap_len + flap_width*flap_width)}"/>
      </inertial>
    </link>

    <joint name="${prefix}_flap_joint" type="revolute">
      <parent link="${prefix}_arm"/>
      <child link="${prefix}_flap"/>
      <origin xyz="${arm_len/2} 0 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="${limit_lower}" upper="${limit_upper}" effort="10.0" velocity="1.0"/>
    </joint>
  </xacro:macro>

  <!-- FIX: Added base_footprint to silence KDL warning about root link inertia -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${chassis_z_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_len} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_z_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_len} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
        <origin xyz="0 0 ${chassis_z_offset}" rpy="0 0 0"/>
        <mass value="${chassis_mass}"/>
        <inertia ixx="${chassis_mass/12.0 * (chassis_width*chassis_width + chassis_height*chassis_height)}" ixy="0.0" ixz="0.0"
                 iyy="${chassis_mass/12.0 * (chassis_len*chassis_len + chassis_height*chassis_height)}" iyz="0.0"
                 izz="${chassis_mass/12.0 * (chassis_len*chassis_len + chassis_width*chassis_width)}"/>
    </inertial>
  </link>

  <xacro:drive_wheel prefix="left" reflect="1"/>
  <xacro:drive_wheel prefix="right" reflect="-1"/>

  <link name="castor_wheel">
    <visual>
      <geometry>
        <sphere radius="${castor_radius}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${castor_radius}"/>
      </geometry>
    </collision>
    <xacro:sphere_inertia m="${castor_mass}" r="${castor_radius}"/>
  </link>

  <joint name="castor_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="castor_wheel"/>
    <origin xyz="${castor_x_offset} 0 ${castor_radius}" rpy="0 0 0"/>
  </joint>

  <link name="vertical_pole">
    <visual>
      <geometry>
        <cylinder radius="0.02" length="0.05"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.02" length="0.05"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.1" r="0.02" h="0.05"/>
  </link>

  <joint name="vertical_pole_joint" type="fixed">
    <parent link="base_link"/>
    <child link="vertical_pole"/>
    <origin xyz="0 0 0.375" rpy="0 0 0"/>
  </joint>

  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.05"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.05"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.3" r="0.05" h="0.05"/>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="vertical_pole"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
  </joint>

  <xacro:collector_arm prefix="left" reflect="1" angle="${arm_angle}" limit_lower="-1.57" limit_upper="0.0"/>
  <xacro:collector_arm prefix="right" reflect="-1" angle="${arm_angle}" limit_lower="0.0" limit_upper="1.57"/>

  <!-- ROS2 CONTROL -->
  <ros2_control name="GazeboSimSystem" type="system">
    <hardware>
      <plugin>gz_ros2_control/GazeboSimSystem</plugin>
    </hardware>
    
    <!-- Wheels -->
    <joint name="left_wheel_joint">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="velocity"/>
      <state_interface name="position"/>
    </joint>

    <joint name="right_wheel_joint">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="velocity"/>
      <state_interface name="position"/>
    </joint>

    <!-- Flaps -->
    <joint name="left_flap_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="right_flap_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <!-- Gazebo Plugin for ros2_control -->
  <gazebo>
    <plugin filename="gz_ros2_control-system" name="gz_ros2_control::GazeboSimROS2ControlPlugin">
      <parameters>$(find ballbot_control)/config/ballbot_controllers.yaml</parameters>
    </plugin>
  </gazebo>

  <gazebo reference="castor_wheel">
    <mu1>0.001</mu1>
    <mu2>0.001</mu2>
  </gazebo>

  <gazebo reference="lidar_link">
    <sensor name="lidar" type="gpu_lidar">
      <pose>0 0 0 0 0 0</pose>
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>10.0</max>
        </range>
      </ray>
      <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
        <render_engine>ogre2</render_engine>
      </plugin>
    </sensor>
  </gazebo>

</robot>